//! Palace migration parity: a `mind-palace.json` written by Node `mpg`
//! must round-trip through scrt's `FilePalace` **byte-for-byte**, so the
//! same file opens in both implementations during migration (COMPAT.md §4).
//!
//! The fixture `tests/palace_fixtures/node-palace.json` was generated by
//! Node `mpg --mp-stash` (+ `--mp-link`, `--mp-ttl`) and checked in. It
//! exercises the tricky cases: two stashes (insertion order), tags, a
//! relation, a TTL `expires_at`, and a **fractional** `source_mtime_ms`
//! (JS `mtimeMs` is a float — the float must serialize identically).

use std::path::PathBuf;

use scrt_core::palace::ops::SystemClock;
use scrt_core::palace::types::Palace as PalaceData;
use scrt_core::palace::{FilePalace, Palace};

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("palace_fixtures")
        .join("node-palace.json")
}

#[test]
fn node_palace_parses_with_expected_shape() {
    let raw = std::fs::read_to_string(fixture_path()).unwrap();
    let p: PalaceData = serde_json::from_str(&raw).unwrap();
    assert_eq!(p.version, 2);
    // Insertion order preserved: auth before db.
    let keys: Vec<&str> = p.stashes.keys().map(String::as_str).collect();
    assert_eq!(keys, vec!["auth", "db"]);
    // The relation survived.
    assert_eq!(p.stashes["auth"].relations.len(), 1);
    assert_eq!(p.stashes["auth"].relations[0].target, "db");
    assert_eq!(p.stashes["auth"].relations[0].rel_type, "depends-on");
    // TTL on db.
    assert!(p.stashes["db"].expires_at.is_some());
    // Fractional mtime preserved as a float.
    let mtime = p.stashes["auth"].nodes[0].source_mtime_ms.unwrap();
    assert!(mtime.fract() != 0.0, "expected fractional mtime, got {mtime}");
}

#[test]
fn node_palace_reserializes_byte_for_byte() {
    let raw = std::fs::read_to_string(fixture_path()).unwrap();
    // serde round-trip: parse then pretty-print + trailing newline, exactly
    // as FilePalace::save writes it.
    let p: PalaceData = serde_json::from_str(&raw).unwrap();
    let out = serde_json::to_string_pretty(&p).unwrap() + "\n";
    assert_eq!(
        out, raw,
        "serde re-serialization diverged from the Node-written file"
    );
}

#[test]
fn file_palace_load_save_is_byte_identical() {
    // Copy the fixture to a temp file, load via FilePalace, save (no
    // mutations), and assert the bytes are unchanged. The snapshot-diff
    // merge must be a no-op when nothing changed.
    let raw = std::fs::read_to_string(fixture_path()).unwrap();
    let dir = std::env::temp_dir().join(format!("scrt-palace-mig-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let target = dir.join("mind-palace.json");
    std::fs::write(&target, &raw).unwrap();

    let mut palace = FilePalace::load(&target, &SystemClock);
    assert!(!palace.is_tainted());
    palace.save().expect("save must succeed");

    let after = std::fs::read_to_string(&target).unwrap();
    let _ = std::fs::remove_dir_all(&dir);
    assert_eq!(after, raw, "FilePalace load+save changed the bytes");
}
