//! Round-trip parity test: scrt's `--format json` and `--format
//! agent-json` output must match the Node `mpg` reference byte-for-byte
//! (modulo COMPAT.md §Excluded: duration_ms -> 0, source.id -> basename).
//!
//! Goldens live in `tests/golden/<corpus>.<case>.json`, generated by
//! `tests/gen_goldens.mjs` against the Node binary and checked in, so this
//! test runs in CI without Node present. Regenerate when the case matrix
//! or reference version changes.

use std::path::PathBuf;

use scrt_core::orchestrator::effort_preset;
use scrt_core::types::{Effort, SearchOptions, SortMode, Strategy, WindowCurve};
use scrt_core::{
    build_agent_envelope, format::format_agent_json, format::format_json, search_with_meta,
    EnvelopeOpts, SearchConfig, SourceInput,
};

#[derive(Clone, Copy)]
enum Fmt {
    Json,
    AgentJson,
}

struct Case {
    name: &'static str,
    effort: Effort,
    clip: Option<usize>,
    max_nodes: Option<usize>,
    max_tokens: Option<usize>,
    strategy: Strategy,
    curve: WindowCurve,
    icase: bool,
    word: bool,
    fuzzy: bool,
    // Documents the case intent; unused because the v0.x CLI builds the
    // envelope with default opts (so no_fill never reaches it). Kept for
    // clarity and for when the server path (Prompt 5) threads it.
    #[allow(dead_code)]
    no_fill: bool,
    fmt: Fmt,
    pattern_override: Option<&'static str>,
}

const fn base(name: &'static str, effort: Effort) -> Case {
    Case {
        name,
        effort,
        clip: None,
        max_nodes: None,
        max_tokens: None,
        strategy: Strategy::Fill,
        curve: WindowCurve::Flat,
        icase: false,
        word: false,
        fuzzy: false,
        no_fill: false,
        fmt: Fmt::Json,
        pattern_override: None,
    }
}

fn cases() -> Vec<Case> {
    vec![
        base("normal", Effort::Normal),
        base("quick", Effort::Quick),
        base("scan", Effort::Scan),
        base("deep", Effort::Deep),
        Case {
            clip: Some(3),
            ..base("scan-clip3", Effort::Scan)
        },
        Case {
            clip: Some(20),
            ..base("scan-clip20", Effort::Scan)
        },
        Case {
            max_nodes: Some(2),
            ..base("maxnodes2", Effort::Scan)
        },
        Case {
            max_tokens: Some(10),
            ..base("maxtokens10", Effort::Normal)
        },
        Case {
            icase: true,
            ..base("icase", Effort::Normal)
        },
        Case {
            word: true,
            ..base("word", Effort::Normal)
        },
        Case {
            curve: WindowCurve::Linear,
            ..base("curve-linear", Effort::Normal)
        },
        Case {
            curve: WindowCurve::Log,
            ..base("curve-log", Effort::Normal)
        },
        Case {
            max_tokens: Some(12),
            strategy: Strategy::Deep,
            ..base("strategy-deep", Effort::Normal)
        },
        Case {
            fmt: Fmt::AgentJson,
            ..base("agentjson-ok", Effort::Normal)
        },
        Case {
            max_nodes: Some(3),
            fmt: Fmt::AgentJson,
            ..base("agentjson-fill", Effort::Scan)
        },
        Case {
            max_nodes: Some(99),
            no_fill: true,
            fmt: Fmt::AgentJson,
            ..base("agentjson-nofill", Effort::Scan)
        },
        Case {
            fmt: Fmt::AgentJson,
            pattern_override: Some("zzznope"),
            ..base("agentjson-nomatch", Effort::Normal)
        },
        Case {
            fuzzy: true,
            clip: Some(10),
            ..base("fuzzy-scan", Effort::Scan)
        },
        Case {
            fuzzy: true,
            clip: Some(10),
            fmt: Fmt::AgentJson,
            ..base("fuzzy-agentjson", Effort::Scan)
        },
    ]
}

const CORPUS: &[(&str, &str)] = &[
    ("basic.txt", "TODO"),
    ("multi.txt", "ab"),
    ("code.txt", "alpha"),
    ("fuzz.txt", "Provider"),
];

fn tests_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests")
}

/// Normalize JSON the same way `gen_goldens.mjs` does: duration_ms -> 0
/// (only if present — the envelope has none), every source.id -> basename.
fn normalize(json: &str) -> String {
    let mut v: serde_json::Value = serde_json::from_str(json).unwrap();
    if let Some(obj) = v.as_object_mut() {
        if obj.contains_key("duration_ms") {
            obj.insert("duration_ms".into(), serde_json::json!(0));
        }
        if let Some(nodes) = obj.get_mut("nodes").and_then(|n| n.as_array_mut()) {
            for n in nodes {
                if let Some(id) = n.pointer_mut("/source/id") {
                    if let Some(s) = id.as_str() {
                        let base = s.replace('\\', "/");
                        let base = base.rsplit('/').next().unwrap_or(&base).to_string();
                        *id = serde_json::json!(base);
                    }
                }
            }
        }
    }
    serde_json::to_string_pretty(&v).unwrap()
}

#[test]
fn roundtrip_against_node_goldens() {
    let tdir = tests_dir();
    let golden_dir = tdir.join("golden");
    let mut checked = 0;
    let mut failures = Vec::new();

    for (file, pattern) in CORPUS {
        let corpus_path = tdir.join("corpus").join(file);
        let corpus_str = corpus_path.to_string_lossy().to_string();
        let stem = file.trim_end_matches(".txt");

        for case in cases() {
            let (pb, pa, pn) = effort_preset(case.effort);
            let opts = SearchOptions {
                case_insensitive: case.icase,
                word_match: case.word,
                ..Default::default()
            };

            let pat = case.pattern_override.unwrap_or(pattern).to_string();
            let config = SearchConfig {
                pattern: pat,
                inputs: vec![SourceInput::Path(corpus_str.clone())],
                effort: case.effort,
                strategy: case.strategy,
                before_tokens: pb,
                after_tokens: pa,
                max_nodes: case.max_nodes.unwrap_or(pn),
                max_tokens: case.max_tokens,
                clip_chars: case.clip,
                sort: SortMode::Default,
                window_curve: case.curve,
                rg_options: opts,
                page: None,
                page_size: None,
                all: false,
                fuzzy: case.fuzzy,
                stdin_content: None,
            };

            let (result, _meta) = search_with_meta(&config).expect("search must succeed");
            // PARITY: the v0.x CLI builds the envelope with NO opts
            // (format.ts:101) — so the test does too.
            let scrt_json = match case.fmt {
                Fmt::Json => format_json(&result),
                Fmt::AgentJson => {
                    format_agent_json(&build_agent_envelope(&result, EnvelopeOpts::default()))
                }
            };
            let scrt_norm = normalize(&scrt_json);

            let golden_path = golden_dir.join(format!("{stem}.{}.json", case.name));
            let golden = std::fs::read_to_string(&golden_path)
                .unwrap_or_else(|_| panic!("missing golden: {}", golden_path.display()));
            let golden_norm = normalize(&golden);

            checked += 1;
            if scrt_norm != golden_norm {
                failures.push(format!(
                    "MISMATCH {stem}/{}\n--- golden ---\n{golden_norm}\n--- scrt ---\n{scrt_norm}",
                    case.name
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {checked} cases diverged:\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
    assert!(checked >= 76, "expected >=76 parity cases, ran {checked}");
}
